# Generated by Django 4.2 on 2026-09-10 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_setup_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=True, help_text='If True, user must change password on next login.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Super Admin'), ('team_lead', 'Team Lead'), ('intern', 'Intern')], default='intern', max_length=20),
        ),
    ]
