# Generated by Django 4.2 on 2026-08-26 15:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('notified_lead', models.BooleanField(default=False)),
                ('attendance_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_checks', to='attendance.attendancesession')),
            ],
            options={
                'db_table': 'availability_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='availabilitycheck',
            index=models.Index(fields=['attendance_session', 'status'], name='availabilit_attenda_6b95f7_idx'),
        ),
        migrations.AddIndex(
            model_name='availabilitycheck',
            index=models.Index(fields=['created_at'], name='availabilit_created_1cab4a_idx'),
        ),
    ]
