# Generated by Django 4.2 on 2026-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breaks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='break',
            name='break_type',
            field=models.CharField(choices=[('lunch', 'Lunch Break'), ('restroom', 'Restroom'), ('training', 'Training'), ('meeting', 'Meeting'), ('personal', 'Personal'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='break',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
