# Generated by Django 4.2 on 2026-09-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='login_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['user', 'status'], name='attendance__user_id_667f3b_idx'),
        ),
    ]
