# Generated by Django 4.2 on 2026-09-10 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendancesession_login_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('force_logged_out', 'Force Logged Out')], default='active', max_length=20),
        ),
    ]
